# Generated by Django 5.0.1 on 2024-11-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubesummary',
            name='target_language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
