# Generated by Django 5.0.1 on 2024-11-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_left', models.IntegerField(default=1500)),
                ('is_running', models.BooleanField(default=False)),
                ('timer_type', models.CharField(default='pomodoro', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
